M48
; DRILL file {KiCad 8.0.8} date 2025-02-05T10:03:45-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-05T10:03:45-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C6.400
%
G90
G05
T1
X154.336Y-115.7
X160.116Y-115.7
T2
X149.2Y-99.5
M30
